// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAntasyftt.Models
{
    public partial class Coach
    {
        public int CId { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Herkunft { get; set; }
        public int TId { get; set; }

        public virtual Team TIdNavigation { get; set; }
    }
}