// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FAntasyftt.Models
{
    public partial class Match
    {
        public Match()
        {
            TId = new HashSet<Team>();
        }

       
        public int MId { get; set; }
        public string Art { get; set; }
        [JsonIgnore]
        public DateOnly? Datum { get; set; }
        [JsonIgnore]
        public TimeOnly? Uhrzeit { get; set; }
        public int SchId { get; set; }
        public int StId { get; set; }

        public virtual Schiedsrichter Sch { get; set; }
        public virtual Stadion St { get; set; }

        public virtual ICollection<Team> TId { get; set; }
    }
}