// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAntasyftt.Models
{
    public partial class Position
    {
        public Position()
        {
            Uebernehmen = new HashSet<Uebernehmen>();
        }

        public int PosId { get; set; }
        public string Bezeichnung { get; set; }

        public virtual ICollection<Uebernehmen> Uebernehmen { get; set; }
    }
}