// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAntasyftt.Models
{
    public partial class Schiedsrichter
    {
        public Schiedsrichter()
        {
            Match = new HashSet<Match>();
        }

        public int SchId { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Herkunft { get; set; }
        public int? Aggressivitaet { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}