// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAntasyftt.Models
{
    public partial class Stadion
    {
        public Stadion()
        {
            Match = new HashSet<Match>();
        }

        public int StId { get; set; }
        public string Name { get; set; }
        public double Kapazitaet { get; set; }
        public int TId { get; set; }

        public virtual Team TIdNavigation { get; set; }
        public virtual ICollection<Match> Match { get; set; }
    }
}