// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FAntasyftt.Models
{
    public partial class Team
    {
        public Team()
        {
            Coach = new HashSet<Coach>();
            Spieler = new HashSet<Spieler>();
            Stadion = new HashSet<Stadion>();
            MId = new HashSet<Match>();
        }

        public int TId { get; set; }
        public string Name { get; set; }
        public string Land { get; set; }
        public string Liga { get; set; }

        [JsonIgnore]
        public virtual ICollection<Coach> Coach { get; set; }
        [JsonIgnore]
        public virtual ICollection<Spieler> Spieler { get; set; }
        [JsonIgnore]
        public virtual ICollection<Stadion> Stadion { get; set; }

        public virtual ICollection<Match> MId { get; set; }
    }
}