// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FAntasyftt.Models
{
    public partial class Uebernehmen
    {
        public int SId { get; set; }
        public int PosId { get; set; }
        public int? Tempo { get; set; }
        public int? Abschluss { get; set; }
        public int? Technik { get; set; }
        public int? Pass { get; set; }
        public int? Verteidigung { get; set; }
        public int? Aggressivitaet { get; set; }
        public int? Reflex { get; set; }
        public int? Ballsicherheit { get; set; }

        public virtual Position Pos { get; set; }
        public virtual Spieler SIdNavigation { get; set; }
    }
}